AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  CSVTrigger:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 90
      Role: 'arn:aws:iam::822069317839:role/service-role/S3FullAccess'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Post'
              - 's3:ObjectCreated:Put'
              - 's3:ObjectCreated:CompleteMultipartUpload'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: archive/
                  - Name: suffix
                    Value: .csv
      Tags:
        Project: ukmon-archive
  Bucket1:
    Type: 'AWS::S3::Bucket'
